[publish]
cmd = ""

[tar-periphery]
description = "Assumes built periphery located at ../komodo/target/release/periphery"
cmd = """
cp ../komodo/target/release/periphery . && \
VERSION=$(./periphery --version | cut -d' ' -f2) && \
tar -czvf periphery-$VERSION.tar.gz periphery periphery.config.toml && \
rm periphery && \
echo "\n$(shasum -a 256 periphery-$VERSION.tar.gz)"
"""